// Information used by resource files
#define INFO_PRODUCT_VERSION_LIST 0,12,1
#define INFO_PRODUCT_VERSION_STRING "0.12.1.0"
#define INFO_FILE_VERSION_LIST INFO_PRODUCT_VERSION_LIST,0
#define INFO_FILE_VERSION_STRING INFO_PRODUCT_VERSION_STRING "." 0
