/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-150-gb5cdf08cae-20210909"
#endif /* AVUTIL_FFVERSION_H */
