#pragma once

enum EaseType
{
	EaseType_Instant,
	EaseType_Linear,
	EaseType_InSine,
	EaseType_OutSine,
	EaseType_InOutSine,
	EaseType_InQuad,
	EaseType_OutQuad,
	EaseType_InOutQuad,
	EaseType_InCubic,
	EaseType_OutCubic,
	EaseType_InOutCubic,
	EaseType_InQuart,
	EaseType_OutQuart,
	EaseType_InOutQuart,
	EaseType_InQuint,
	EaseType_OutQuint,
	EaseType_InOutQuint,
	EaseType_InExpo,
	EaseType_OutExpo,
	EaseType_InOutExpo,
	EaseType_InCirc,
	EaseType_OutCirc,
	EaseType_InOutCirc,
	EaseType_InBack,
	EaseType_OutBack,
	EaseType_InOutBack,
	EaseType_InElastic,
	EaseType_OutElastic,
	EaseType_InOutElastic,
	EaseType_InBounce,
	EaseType_OutBounce,
	EaseType_InOutBounce,
	EaseType_Count
};